
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
FanPadDetector.py

Geometry model for the P2 BASKET fan-pad Micromegas detector.

Each pad is a rectangle defined by two radial endpoints:
  - outer  (x, y)       : B_Cu trace endpoint (far from connector)
  - inner  (via_x, via_y): via position (F_Cu ↔ B_Cu transition)

The rectangle is oriented along the via→outer direction (radial), with a
fixed angular half-width set at construction time (~5 mm for ~1 cm pads).

Channel mapping is embedded at load time:
  (vmm_id, ch) → pad index
with support for 'normal' (ch = mec8_pin − 3) or 'flipped' (ch = 66 − mec8_pin)
orientation, to handle unknown FEB pin-order direction.

Usage
-----
    from FanPadDetector import FanPadDetector

    det = FanPadDetector.from_mapping_csv(
        csv_path    = "Detector_Mapping/P2_BASKET/P2_BASKET_mapping.csv",
        mec8_to_vmm = {(6, 1): 12, (6, 0): 13, (7, 1): 14, (7, 0): 15},
        fpc_connectors = [6, 7],
        orientation = "normal",   # or "flipped"
        half_width_mm = 5.0,
    )
    fig, axes = det.plot_hit_heatmap(df_hits_per_channel)
    fig, axes = det.plot_efficiency_map(df_ch_eff)

@author: ak271430
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches


# ─────────────────────────────────────────────────────────────
# PAD PRIMITIVE
# ─────────────────────────────────────────────────────────────

class FanPad:
    """
    Single fan-shaped detector pad defined by its two radial endpoints.

    Parameters
    ----------
    outer_x, outer_y : float
        Outer endpoint (B_Cu trace end, far from the FPC connector).
    via_x, via_y : float
        Inner endpoint (via position, near the FPC connector side).
    half_width : float
        Half-width in the angular direction (mm).
    vmm_id : int
    ch : int
        VMM id and channel that read this pad.
    """
    __slots__ = ("outer_x", "outer_y", "via_x", "via_y",
                 "half_width", "vmm_id", "ch")

    def __init__(self, outer_x, outer_y, via_x, via_y,
                 half_width, vmm_id, ch):
        self.outer_x   = outer_x
        self.outer_y   = outer_y
        self.via_x     = via_x
        self.via_y     = via_y
        self.half_width = half_width
        self.vmm_id    = vmm_id
        self.ch        = ch

    @property
    def center(self):
        return (0.5 * (self.outer_x + self.via_x),
                0.5 * (self.outer_y + self.via_y))

    @property
    def half_length(self):
        return 0.5 * np.hypot(self.outer_x - self.via_x,
                               self.outer_y - self.via_y)

    @property
    def rotation(self):
        """Angle (rad) from via toward outer endpoint."""
        return np.arctan2(self.outer_y - self.via_y,
                          self.outer_x - self.via_x)

    def vertices(self):
        """4 corners of the pad rectangle in detector coordinates."""
        cx, cy = self.center
        hl = self.half_length
        hw = self.half_width
        rot = self.rotation
        corners = np.array([
            [-hl, -hw], [hl, -hw], [hl, hw], [-hl, hw],
        ], dtype=float)
        c, s = np.cos(rot), np.sin(rot)
        R = np.array([[c, -s], [s, c]])
        return corners @ R.T + np.array([cx, cy])


# ─────────────────────────────────────────────────────────────
# DETECTOR MODEL
# ─────────────────────────────────────────────────────────────

class FanPadDetector:
    """
    P2 BASKET fan-pad Micromegas detector model.

    Attributes
    ----------
    pads : list of FanPad
        All active pads, in load order.
    channel_map : dict
        (vmm_id, ch) → pad index in self.pads.
    apex : (float, float)
        Fan apex position (mm) used for polar coordinates.
    orientation : str
        'normal' or 'flipped' — VMM channel assignment direction.
    """

    def __init__(self):
        self.pads        = []
        self.channel_map = {}
        self.apex        = (0.0, 0.0)
        self.orientation = "normal"

    # ── Construction ─────────────────────────────────────────

    @classmethod
    def from_mapping_csv(cls, csv_path, mec8_to_vmm, fpc_connectors,
                         orientation="normal", half_width_mm=5.0):
        """
        Build detector from P2_BASKET_mapping.csv.

        Parameters
        ----------
        csv_path : str
            Path to CSV generated by P2_mapping.py (must have via_x, via_y).
        mec8_to_vmm : dict
            {(fpc_connector, mec8_connector): vmm_id}
        fpc_connectors : list of int
            FPC connector numbers that were cabled (subset of 0–9).
        orientation : {'normal', 'flipped'}
            'normal'  → ch = mec8_pin − 3   (pin 3 = ch 0)
            'flipped' → ch = 66 − mec8_pin  (pin 3 = ch 63)
        half_width_mm : float
            Half-width of each pad in the angular direction (default 5 mm).
        """
        df = pd.read_csv(csv_path)
        df = df[df["connector_number"].isin(fpc_connectors)].copy()
        df = df.dropna(subset=["x", "y", "via_x", "via_y",
                                "mec8_connector", "mec8_pin"])

        det = cls()
        det.orientation = orientation

        # Recover apex from polar coordinates if available
        if "phi" in df.columns and "radius" in df.columns:
            row0 = df.iloc[0]
            det.apex = (
                row0["x"] - row0["radius"] * np.cos(row0["phi"]),
                row0["y"] - row0["radius"] * np.sin(row0["phi"]),
            )

        for _, row in df.iterrows():
            fpc  = int(row["connector_number"])
            mec8 = int(row["mec8_connector"])
            pin  = int(row["mec8_pin"])

            vmm_id = mec8_to_vmm.get((fpc, mec8))
            if vmm_id is None:
                continue

            if orientation == "normal":
                ch = pin - 3
            else:
                ch = 66 - pin

            if not (0 <= ch <= 63):
                continue

            pad = FanPad(
                outer_x   = float(row["x"]),
                outer_y   = float(row["y"]),
                via_x     = float(row["via_x"]),
                via_y     = float(row["via_y"]),
                half_width = half_width_mm,
                vmm_id    = vmm_id,
                ch        = ch,
            )
            idx = len(det.pads)
            det.pads.append(pad)
            det.channel_map[(vmm_id, ch)] = idx

        print(f"FanPadDetector: loaded {len(det.pads)} pads "
              f"(orientation={orientation})")
        return det

    @classmethod
    def from_mapping_csv_full(cls, csv_path, half_width_mm=5.0,
                              fpc_connectors=None):
        """
        Load the full detector geometry for display and geometry testing.

        No VMM wiring required.  Uses connector_number as pseudo-vmm_id and
        (strip − 1) as ch so the full 1280-pad fan can be visualised.

        Parameters
        ----------
        csv_path : str
            Path to CSV generated by P2_mapping.py (must have via_x, via_y).
        half_width_mm : float
            Half-width of each pad in the angular direction (default 5 mm).
        fpc_connectors : list of int or None
            Subset of connectors to load (default: all present in the CSV).
        """
        df = pd.read_csv(csv_path)
        if fpc_connectors is not None:
            df = df[df["connector_number"].isin(fpc_connectors)].copy()
        df = df.dropna(subset=["x", "y", "via_x", "via_y"])

        det = cls()
        det.orientation = "geometry_only"

        if "phi" in df.columns and "radius" in df.columns:
            row0 = df.iloc[0]
            det.apex = (
                row0["x"] - row0["radius"] * np.cos(row0["phi"]),
                row0["y"] - row0["radius"] * np.sin(row0["phi"]),
            )

        for _, row in df.iterrows():
            fpc   = int(row["connector_number"])
            strip = int(row["strip"]) if "strip" in df.columns else 1
            ch    = strip - 1          # 0-indexed strip within connector (0–127)

            pad = FanPad(
                outer_x    = float(row["x"]),
                outer_y    = float(row["y"]),
                via_x      = float(row["via_x"]),
                via_y      = float(row["via_y"]),
                half_width = half_width_mm,
                vmm_id     = fpc,
                ch         = ch,
            )
            idx = len(det.pads)
            det.pads.append(pad)
            det.channel_map[(fpc, ch)] = idx

        n_conn = df["connector_number"].nunique()
        print(f"FanPadDetector: loaded {len(det.pads)} pads "
              f"({n_conn} FPC connectors, geometry_only)")
        return det

    # ── Plotting helpers ──────────────────────────────────────

    def _draw_pads(self, ax, values, cmap, norm, missing_color="lightgrey"):
        """
        Draw all pads as rotated rectangles coloured by values[i].

        Parameters
        ----------
        values : array-like, length = len(self.pads)
            One value per pad; np.nan → missing_color.
        """
        for pad, val in zip(self.pads, values):
            verts = pad.vertices()
            color = (cmap(norm(val))
                     if np.isfinite(val) and val >= 0
                     else missing_color)
            poly = plt.Polygon(verts,
                               facecolor=color,
                               edgecolor="black",
                               linewidth=0.3,
                               zorder=2)
            ax.add_patch(poly)

        # Auto-set limits
        all_x = [p.outer_x for p in self.pads] + [p.via_x for p in self.pads]
        all_y = [p.outer_y for p in self.pads] + [p.via_y for p in self.pads]
        margin = 20
        ax.set_xlim(min(all_x) - margin, max(all_x) + margin)
        ax.set_ylim(min(all_y) - margin, max(all_y) + margin)
        ax.set_aspect("equal")
        ax.set_xlabel("X (mm)")
        ax.set_ylabel("Y (mm)")

    # ── Public plot methods ───────────────────────────────────

    def plot_hit_heatmap(self, df_ch_stats, run_no=None,
                         detector_label="P2 Large Detector",
                         out_dir=None):
        """
        Two-panel plot: hit count (left) and total ADC (right) per pad.

        Parameters
        ----------
        df_ch_stats : pd.DataFrame
            Must have columns vmm_id, ch, n_hits, adc_sum.
            Output of compute_pad_hit_stats() accumulated over all files.
        run_no : int or None
        detector_label : str
        out_dir : str or None
        """
        hit_map = {}
        adc_map = {}
        for _, row in df_ch_stats.iterrows():
            key = (int(row["vmm_id"]), int(row["ch"]))
            idx = self.channel_map.get(key)
            if idx is not None:
                hit_map[idx] = row["n_hits"]
                adc_map[idx] = row["adc_sum"]

        n = len(self.pads)
        hit_vals = np.array([hit_map.get(i, np.nan) for i in range(n)])
        adc_vals = np.array([adc_map.get(i, np.nan) for i in range(n)])

        fig, axes = plt.subplots(1, 2, figsize=(18, 9))

        for ax, vals, title, cmap_obj in [
            (axes[0], hit_vals, "Hit count",         plt.cm.viridis),
            (axes[1], adc_vals, "Total ADC (charge)", plt.cm.viridis),
        ]:
            valid = vals[np.isfinite(vals)]
            vmax  = valid.max() if len(valid) else 1.0
            norm  = plt.Normalize(vmin=0, vmax=vmax)
            self._draw_pads(ax, vals, cmap_obj, norm)

            sm = plt.cm.ScalarMappable(cmap=cmap_obj, norm=norm)
            sm.set_array([])
            fig.colorbar(sm, ax=ax, shrink=0.8, label=title)
            ax.set_title(title, fontsize=11)

        run_str = f"  |  Run {run_no}" if run_no is not None else ""
        fig.suptitle(f"{detector_label} — pad hit heatmaps{run_str}",
                     fontsize=13, fontweight="bold")
        plt.tight_layout()

        if out_dir is not None:
            import os
            os.makedirs(out_dir, exist_ok=True)
            stem = f"hit_map_{detector_label.replace(' ', '_')}_run{run_no}"
            for ext in ("png", "pdf"):
                fig.savefig(os.path.join(out_dir, f"{stem}.{ext}"),
                            bbox_inches="tight")
        return fig, axes

    def plot_efficiency_map(self, df_ch_eff, run_no=None,
                            detector_label="P2 Large Detector",
                            out_dir=None):
        """
        Per-pad hit-rate map coloured by true_efficiency.

        Parameters
        ----------
        df_ch_eff : pd.DataFrame
            Must have columns vmm_id, ch, true_efficiency.
        """
        eff_map = {}
        for _, row in df_ch_eff.iterrows():
            key = (int(row["vmm_id"]), int(row["ch"]))
            idx = self.channel_map.get(key)
            if idx is not None:
                val = max(0.0, float(row["true_efficiency"]))
                eff_map[idx] = val

        n = len(self.pads)
        eff_vals = np.array([eff_map.get(i, np.nan) for i in range(n)])

        valid = eff_vals[np.isfinite(eff_vals)]
        vmax  = valid.max() if len(valid) else 1.0
        cmap  = plt.cm.RdYlGn
        norm  = plt.Normalize(vmin=0, vmax=vmax)

        fig, ax = plt.subplots(figsize=(10, 9))
        self._draw_pads(ax, eff_vals, cmap, norm)

        sm = plt.cm.ScalarMappable(cmap=cmap, norm=norm)
        sm.set_array([])
        cb = fig.colorbar(sm, ax=ax, shrink=0.8)
        cb.set_label("Hit rate per trigger (relative, normalised to data max)")
        cb.formatter = plt.FuncFormatter(lambda x, _: f"{x*100:.3f}%")
        cb.update_ticks()

        run_str = f"  |  Run {run_no}" if run_no is not None else ""
        ax.set_title(
            f"{detector_label} — pad hit-rate map{run_str}\n"
            f"(max = {vmax*100:.3f}%)",
            fontsize=12, fontweight="bold",
        )
        plt.tight_layout()

        if out_dir is not None:
            import os
            os.makedirs(out_dir, exist_ok=True)
            stem = f"eff_map_{detector_label.replace(' ', '_')}_run{run_no}"
            for ext in ("png", "pdf"):
                fig.savefig(os.path.join(out_dir, f"{stem}.{ext}"),
                            bbox_inches="tight")
        return fig, ax

    def plot_geometry(self, ax=None, color="lightblue", label_pads=False):
        """Quick geometry check: draw all pads with uniform colour."""
        if ax is None:
            fig, ax = plt.subplots(figsize=(10, 9))
        dummy = np.zeros(len(self.pads))
        cmap = plt.cm.Blues
        norm = plt.Normalize(vmin=0, vmax=1)
        self._draw_pads(ax, dummy, cmap, norm, missing_color=color)
        if label_pads:
            for pad in self.pads:
                cx, cy = pad.center
                ax.text(cx, cy, f"({pad.vmm_id},{pad.ch})",
                        fontsize=3, ha="center", va="center")
        ax.set_title(f"FanPadDetector geometry — {len(self.pads)} pads  "
                     f"(orientation={self.orientation})",
                     fontsize=11)
        return ax
