universe                = vanilla
executable              = urwtb_job.sh
arguments               = "$(run) $(sub_run) $(tbins)"
should_transfer_files   = YES
when_to_transfer_output = ON_EXIT
transfer_input_files    = urwcode.tgz
transfer_output_files   = products.tgz
transfer_output_remaps  = "products.tgz = products/urwtb.$(run).$(sub_run).tgz"
output                  = logs/urwtb.$(run).$(sub_run).out
error                   = logs/urwtb.$(run).$(sub_run).err
log                     = logs/urwtb_condor.$(ClusterId).log
request_cpus            = 1
request_memory          = 8000
request_disk            = 10000000
MY.SendCredential       = true
max_retries             = 2
retry_until             = (ExitCode =!= 1)
flavour                 = longlunch
MY.JobFlavour           = "$(flavour)"
queue run,sub_run,tbins from urwtb_joblist.txt
