name: Sync to GitLab

on:
  push:
    branches: [ "main" ]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to GitLab Mirror
        run: |
          git push --prune https://<your-gitlab-username>:${{ secrets.GITLAB_TOKEN }}@drf-gitlab.cea.fr/p2/vmm-analysis-extended.git +refs/heads/*:refs/heads/* +refs/tags/*:refs/tags/*
