name: Sync to GitLab

on:
  push:
    branches: [ "main" ]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Push to Private GitLab Mirror
        run: |
          # We force git to use the token for authentication explicitly
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git push --force --prune https://akallitss:${{ secrets.GITLAB_TOKEN }}@drf-gitlab.cea.fr/p2/vmm-analysis-extended.git main:main
